title: CAMeL Deadlines # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to deadlines for CAMeLeers
author: Go Inoue

domain: "https://go-inoue.github.io/camel-deadlines/"
baseurl: /camel-deadlines

twitter_username: abhshkdz
twitter_hashtag: machinelearning
github_username: go-inoue
github_repo: camel-deadlines

markdown: kramdown
#ga_id: UA-36274081-2

include: ['_pages']
