title: NLP Conference Deadlines for CAMeLers # (Maintained by @abhshkdz)
# email: abhshkdz@vt.edu
description: Countdowns to top NLP conference deadlines
author: Go Inoue

domain:
baseurl: "https://go-inoue.github.io/camel-deadlines"

twitter_username:
twitter_hashtag:
github_username: go-inoue
github_repo: camel-deadlines

markdown:
ga_id:
